version: '3'
services:
  mysql_master:
    image: mysql:8.0
    env_file:
      - ./master.env
    container_name: "mysql_master"
    restart: "no"
    ports:
      - 4406:3306
    volumes:
      - ./conf-master/mysql.conf.cnf:/etc/mysql/conf.d/mysql.conf.cnf
      - ./conf-master/data:/var/lib/mysql
    networks:
      - overlay

  mysql_slave:
    image: mysql:8.0
    env_file:
      - ./slave.env
    container_name: "mysql_slave"
    restart: "no"
    ports:
      - 5506:3306
    depends_on:
      - mysql_master
    volumes:
      - ./conf-slave/mysql.conf.cnf:/etc/mysql/conf.d/mysql.conf.cnf
      - ./conf-slave/data:/var/lib/mysql
    networks:
      - overlay

networks:
  overlay:
